# Header
menu:
  Home: /
  Archives: /archives
  About: /about
rss: /atom.xml

menu_icon:
  Home: fa-home
  Archives: fa-archive
  About: fa-user

# Content
excerpt_link: Read More
fancybox: false

#your personal image
your_img: https://en.gravatar.com/userimage/65307196/5c4903f7ca1880b5f7b2f6afe86e5f06.jpeg?size=150

# Miscellaneous
google_analytics: 
favicon: favicon.png 
twitter:
google_plus:
fb_admins:
fb_app_id: